"""Generate NOTES.md from the pipeline outputs, so every number in it is traceable.

Usage: python notes.py   (after fetch, prepare, sim.run, sim.validate, render.pathway, renders)
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

from common import MANIFEST, OUT, PREPARE_LOG, RESULTS, load_json
from sim.model import Params

ROOT = Path(__file__).resolve().parent


def ffprobe(path: Path) -> dict | None:
    if not path.exists():
        return None
    r = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries",
                        "stream=width,height,r_frame_rate,codec_name,profile,pix_fmt,nb_frames:format=duration,size,bit_rate",
                        "-of", "json", str(path)], capture_output=True, text=True)
    if r.returncode:
        return None
    j = json.loads(r.stdout)
    s, f = j["streams"][0], j["format"]
    return dict(w=s["width"], h=s["height"], fps=s["r_frame_rate"], codec=f"{s['codec_name']} {s.get('profile', '')}".strip(),
                pix=s["pix_fmt"], dur=float(f["duration"]), mb=int(f["size"]) / 1e6, mbps=int(f.get("bit_rate", 0)) / 1e6)


def fmt_mean_sd(x):
    return f"{x['mean']:.1f} ± {x['sd']:.1f}"


def main():
    man = load_json(MANIFEST)
    prep = load_json(PREPARE_LOG)
    exp = load_json(RESULTS / "experiments.json")
    val = load_json(RESULTS / "validation.json")
    pw = load_json(RESULTS / "pathway.json")
    nums = load_json(RESULTS / "film_numbers.json")
    p = Params()
    conds = exp["conditions"]
    n, c, pos, rs = prep["neurons"], prep["connectivity"], prep["positions"], prep["render_space"]
    tr = prep["transmitters"]
    L = []
    w = L.append

    w("# A THOUGHT — notes\n")
    w("A film of a whole-brain simulation of the fruit fly *Drosophila melanogaster*, built on the complete published "
      "wiring diagram (FlyWire, release 783). Every flash of light in the film is a spike produced by the simulation; "
      "every number on screen comes from the data or from the simulation output. This file is generated by "
      "`python notes.py` from the pipeline's result files.\n")
    w("On-screen wording used throughout: *\"A simulation built on the real wiring of a fruit fly's brain\"* "
      "(never \"a real fly's thoughts\").\n")

    # ------------------------------------------------------------------ deliverables
    w("## 1. Deliverables\n")
    w("| file | content | video |\n|---|---|---|")
    for name, what in [("a_thought.mp4", "master, ~2:36"), ("a_thought_1080p.mp4", "1080p version of the master"),
                       ("a_thought_vertical.mp4", "vertical cut, ~60 s"), ("poster.png", "long exposure of all spikes")]:
        info = ffprobe(OUT / name) if name.endswith(".mp4") else None
        if name.endswith(".png"):
            exists = (OUT / name).exists()
            w(f"| `out/{name}` | {what} | {'3840×2160 PNG' if exists else 'not rendered yet'} |")
        elif info:
            w(f"| `out/{name}` | {what} | {info['w']}×{info['h']}, {info['fps']} fps, {info['dur']:.2f} s, "
              f"{info['codec']}, {info['pix']}, {info['mb']:.0f} MB ({info['mbps']:.1f} Mb/s) |")
        else:
            w(f"| `out/{name}` | {what} | not rendered yet |")
    w("")

    # ------------------------------------------------------------------ sources
    w("## 2. Data and code sources\n")
    w("All raw files are downloaded by `fetch.py` into `data/raw/` and recorded in `data/manifest.json` "
      "(URL, retrieval time, version / commit, size, SHA-256). FlyWire release: **783**.\n")
    w("| key | version | size (bytes) | SHA-256 | retrieved (UTC) |\n|---|---|---:|---|---|")
    for k, v in man["files"].items():
        w(f"| `{k}` | {v['version']} | {v['size_bytes']:,} | `{v['sha256']}` | {v['retrieved_utc']} |")
    w("")
    w("URLs (all fetched over HTTPS):\n")
    for k, v in man["files"].items():
        w(f"- `{k}`: {v['url']}")
        for mem, e in (v.get("extracted") or {}).items():
            w(f"  - extracted `{mem}` → `{e['path']}` ({e['size_bytes']:,} B, SHA-256 `{e['sha256']}`)")
    w("")
    w("**Official sources that could not be reached from the build environment** (the network policy of the "
      "environment returned HTTP 403 for these hosts; each attempt is logged in the manifest):\n")
    for u in man["unreachable_official_sources"]:
        w(f"- {u['role']}: {u['url']} — {u['status'].split(':')[0]}. Substitute: {u['substitute']}.")
    w("")
    w("Why the substitute connection table is faithful: the authors of the model publish their own aggregation of "
      "release 783 (`Connectivity_783.parquet`: one row per connected neuron pair, synapse count, sign). "
      "flypoke builds its network from the official Zenodo table instead. Running flypoke's own, unmodified code on a "
      "matrix rebuilt from the authors' table (≥ 5 synapses, annotation `top_nt` signs, exactly flypoke's recipe) "
      f"reproduces flypoke's published results table **exactly** (all twelve numbers; section 6c). The two tables "
      "therefore agree on every connection that matters for these experiments.\n")
    sk = man.get("skeletons", {})
    if sk:
        w(f"Skeletons of the {len(sk)} pathway neurons were read from the public FlyWire release-783 segmentation "
          "bucket (`https://storage.googleapis.com/flywire_v141_m783/skeletons_mip_1`, neuroglancer sharded "
          "precomputed format; reader in `render/pathway.py`) because the official skeleton download (Zenodo "
          "10877326) was unreachable. Each is recorded in the manifest with shard URL, byte range and SHA-256 of the "
          "decoded skeleton; they are resampled to one vertex per 1.5 µm along each branch for drawing.\n")
    w("### Licence and citation terms\n")
    w("- **FlyWire data** (connectome, annotations, skeletons): citation of Dorkenwald et al. 2024 and Schlegel et al. "
      "2024 is required; annotation versions ≥ 3.0.0 also ask for Berg et al. 2025 and Matsliah et al. 2024 "
      "(flywire_annotations README, \"How to cite\"). The flywire_annotations repository has no LICENSE file. "
      "flypoke's README states that FlyWire data are released under **CC BY 4.0**; the primary licence pages "
      "(Zenodo record 10676866, flywire.ai, codex.flywire.ai) were not reachable from this environment, so the exact "
      "licence wording is **unverified here and must be confirmed before public release**. The credits follow the "
      "citation requirements above.")
    w("- **Shiu et al. model code and v783 files**: MIT License, © 2023 Philip Shiu and Nico Spiller.")
    w("- **flypoke**: MIT License, © 2026 vshapenko (used only for cross-checks).")
    w("- **navis-flybrains** (brain mesh): GNU GPL v3 (package). The FLYWIRE meshes are data derived from the FAFB14 "
      "neuropil mesh transformed into FlyWire space (flybrains documentation).")
    w("- **Inter** typeface: SIL Open Font License (Ubuntu package `fonts-inter`).\n")

    # ------------------------------------------------------------------ neurons
    w("## 3. Neurons and positions\n")
    w(f"- Neurons simulated: **{n['simulated_total']:,}** = union of the annotation table v3.1.0 ({n['annotation_v3_1_0']:,} "
      f"neurons), the paper-version table v2.1.0 ({n['annotation_v2_1_0_paper_version']:,} neurons — the proofread neuron "
      f"count of release 783 reported by Dorkenwald et al. 2024) and the authors' v783 model ({n['authors_v783_model']:,} "
      "neurons, i.e. all neurons with at least one connection).")
    w(f"- {n['authors_model_not_in_v3_1_0']} neurons of the authors' model are no longer listed in annotation v3.1.0; their "
      f"annotation (and position) is taken from v2.1.0. {n['v3_1_0_only']} neurons exist only in v3.1.0. "
      f"{n['without_connections']:,} neurons have no connection in the authors' table and therefore never receive input; "
      "they are simulated anyway and drawn at rest.")
    w(f"- Positions: soma coordinates for **{pos['soma']:,}** neurons, the annotation's anchor point (\"typically on the "
      f"backbone of the neuron\") for **{pos['anchor_point_no_soma']:,}** neurons without an annotated soma, none missing "
      f"(**{pos['no_position']}** neurons without a position; nothing excluded from rendering). Sensory neurons have their "
      "somata outside the brain, so they are drawn at their anchor point where they enter the brain.")
    ax = rs["axes"]
    ev = ax["evidence_nm"]
    w(f"- Coordinates are 4 × 4 × 40 nm voxels, converted to nm and then to a render space centred on the brain mesh and "
      f"scaled so the largest half-extent is 1 (scale {rs['scale_per_nm']:.4e} per nm; centre "
      f"{', '.join(f'{x:,.0f}' for x in rs['center_nm'])} nm). Axis directions were determined from the data: x grows "
      f"towards the fly's right (mean x of right/left neurons {ev['mean_x_right']:,.0f} / {ev['mean_x_left']:,.0f} nm), "
      f"y grows ventrally (gustatory afferents {ev['mean_y_gustatory']:,.0f} nm vs pars intercerebralis + ocellar neurons "
      f"{ev['mean_y_PI_ocellar']:,.0f} nm), z grows posteriorly (olfactory receptor neurons {ev['mean_z_olfactory']:,.0f} nm vs "
      f"Kenyon cells {ev['mean_z_kenyon']:,.0f} nm). Render frame: {rs['frame']}. Left and right follow the annotation's "
      "`side` column.")
    w(f"- Brain shell: `FLYWIRE_whole_brain.ply` from navis-flybrains 0.6.3 ({prep['shell']['vertices']:,} vertices, "
      f"{prep['shell']['faces']:,} faces), in the same nm space; all positioned neurons lie inside its bounding box.\n")

    # ------------------------------------------------------------------ connectivity
    w("## 4. Connectivity and transmitter signs\n")
    w(f"- Connections (neuron pairs with ≥ 1 synapse): **{c['connections']:,}**; synapses: **{c['synapses']:,}**; "
      f"{c['excitatory_connections']:,} excitatory, {c['inhibitory_connections']:,} inhibitory. No synapse threshold is "
      f"applied (the authors' v783 table contains every pair, minimum {c['min_synapses_per_connection']} synapse). For "
      f"reference: {c['connections_ge5_synapses']:,} connections have ≥ 5 synapses ({c['synapses_in_connections_ge5']:,} synapses).")
    w("- Weight of a connection = sign(presynaptic neuron) × synapse count × w_syn. The sign is the authors' `Excitatory` "
      "column (constant per presynaptic neuron): acetylcholine → excitatory, GABA and glutamate → inhibitory, other "
      "transmitters (dopamine, serotonin, octopamine) → excitatory (as in the paper and in flypoke).")
    mism = tr["sign_disagrees_with_top_nt"]
    w(f"- The authors' signs disagree with the per-neuron `top_nt` of annotation v3.1.0 for {mism:,} neurons (e.g. "
      f"{tr['annotation_top_nt_vs_model_sign']['acetylcholine|-1']:,} ACh neurons are inhibitory and "
      f"{tr['annotation_top_nt_vs_model_sign']['glutamate|1']:,} glutamate / {tr['annotation_top_nt_vs_model_sign']['gaba|1']:,} "
      "GABA neurons excitatory in the authors' table), presumably because the authors aggregated the synapse-level "
      "transmitter predictions differently. The simulation follows the authors' file (\"exactly as implemented\"); the "
      "colour of a spike shows what the neuron does in the simulation (section 7). flypoke's convention (annotation "
      "`top_nt`) is evaluated as a cross-check.\n")

    # ------------------------------------------------------------------ model
    w("## 5. Model\n")
    w("`sim/model.py` re-implements, step by step, the Brian2 model in the authors' `model.py` (commit "
      "`91bdd1e`), with a scipy.sparse CSR matrix for synaptic input and vectorised NumPy updates. Every parameter is "
      "taken from `default_params` in that file (a unit test parses the file and compares):\n")
    w("| parameter | value | authors' comment |\n|---|---|---|")
    rows = [("t_run", f"{p.t_run:g} ms", "duration of trial"), ("n_run", f"{p.n_run}", "number of runs"),
            ("v_0", f"{p.v_0:g} mV", "resting potential"), ("v_rst", f"{p.v_rst:g} mV", "reset potential after spike"),
            ("v_th", f"{p.v_th:g} mV", "threshold for spiking"), ("t_mbr", f"{p.t_mbr:g} ms", "membrane time scale"),
            ("tau", f"{p.tau:g} ms", "time constant (synaptic)"), ("t_rfc", f"{p.t_rfc:g} ms", "refractory period"),
            ("t_dly", f"{p.t_dly:g} ms", "delay for changes in post-synaptic neuron"),
            ("w_syn", f"{p.w_syn:g} mV", "weight per synapse (free parameter)"),
            ("r_poi", f"{p.r_poi:g} Hz", "rate of the Poisson inputs"), ("f_poi", f"{p.f_poi:g}", "scaling factor for Poisson synapse"),
            ("dt", f"{p.dt:g} ms", "Brian2 default clock (model.py does not set it)")]
    for a, b, cmt in rows:
        w(f"| `{a}` | {b} | {cmt} |")
    w("")
    w("Equations (verbatim): `dv/dt = (v_0 - v + g) / t_mbr : volt (unless refractory)`, "
      "`dg/dt = -g / tau : volt (unless refractory)`; threshold `v > v_th`; reset `v = v_rst; g = 0`; "
      "`Synapses(on_pre='g += w', delay=t_dly)`; `PoissonInput(target_var='v', N=1, rate=r_poi, weight=w_syn*f_poi)`; "
      "stimulated neurons have refractory period 0; integration `method='linear'` (exact).\n")
    w("Per 0.1 ms step, in Brian2's schedule order: (1) exact update of (v, g) for non-refractory neurons, refractory "
      "neurons frozen; (2) threshold; (3) delayed synaptic events (round(1.8 / 0.1) = 18 steps) are added to g — "
      "**except for postsynaptic neurons that are refractory**: Brian2 masks synaptic updates of variables flagged "
      "`(unless refractory)`, so input arriving during the refractory period is discarded (found by comparing with "
      "Brian2 and confirmed in Brian2's generated code: `add.at(g, post[not_refractory], w[not_refractory])`); "
      "Poisson input adds 68.75 mV to v with probability rate × dt; (4) reset. A Poisson event therefore forces a spike "
      "one step later.\n")
    w("Recording: every spike of every neuron (step index, neuron index), per trial, stored compressed in "
      "`results/spikes/<condition>.npz`.\n")

    # ------------------------------------------------------------------ stimulus
    g = load_json(ROOT / "data/processed/groups.json")
    w("## 6. Stimuli, experiments and validation\n")
    w("### Stimulus identification\n")
    sides = lambda d: ", ".join(f"{v} {k}" for k, v in sorted(d.items()))
    w(f"- Annotation classes (v3.1.0), identical to flypoke's `feeding` selectors: `cell_sub_class == 'sugar/water'` "
      f"{g['sugar']['n']} neurons ({sides(g['sugar']['by_side'])}), `cell_sub_class == 'bitter'` {g['bitter']['n']} "
      f"({sides(g['bitter']['by_side'])}), ingestion motor neurons {g['ingestion_motor_neurons']['n']}. In the paper-version "
      f"annotation v2.1.0 these classes have {g['annotation_v2.1.0_counts']['sugar_water']} and "
      f"{g['annotation_v2.1.0_counts']['bitter']} neurons.")
    w(f"- **MN9**: there is no `cell_type == 'MN9'` in any annotation version. Shiu et al. use root id "
      f"{g['mn9']['shiu_mn9_root_id']} for MN9 (figures.ipynb); in release 783 that id is unchanged and annotated "
      f"`cell_type` **CB0701** (ingestion motor neuron). CB0701 has exactly {g['mn9']['n']} neurons, one per side "
      f"({', '.join(str(r) for r in g['mn9']['root_ids'])}; sides {', '.join(g['mn9']['sides'])}); both are treated as "
      "MN9, as in flypoke.")
    w(f"- **Film stimuli: the GRN lists of Shiu et al.** (figures.ipynb, snapshot 630): 21 sugar-sensing and 21 "
      f"bitter-sensing labellar GRNs; {exp['stimulus']['sugar_n']} and {exp['stimulus']['bitter_n']} of these root ids exist "
      f"unchanged in release 783 and are used (all annotated `{exp['stimulus']['sugar_annotation'][0]}` and "
      f"`{exp['stimulus']['bitter_annotation'][0]}` respectively). The annotation cannot separate sugar from water GRNs "
      "(both are cell type LB3); the paper identified sugar GRNs by connectivity. The paper calls them \"right "
      "hemisphere\"; annotation v3.1.0 lists all of them as side = left (and Shiu et al.'s \"left\" MN9 as right), i.e. "
      "the two sources name the sides in mirror image. The film avoids calling the input left or right; the MN9 "
      "readout uses the annotation's sides.")
    w("- **Why not the whole annotation classes for the film:** in the exact model (no synapse threshold) stimulating "
      "all 129 sugar/water GRNs also drives the olfactory system and mushroom bodies into sustained activity "
      "(section 6c, last table): thousands of neurons fire, a regime not reported in the paper and not a depiction of "
      "tasting sugar. The paper's own stimulus sets give the published focal response. The annotation classes are run "
      "as documented cross-checks.\n")

    w("### Experiments\n")
    w(f"Each condition: {conds['A_sugar']['n_trials']} trials of 1 s, seeds 0–{conds['A_sugar']['n_trials'] - 1}, Poisson "
      f"input at {exp['stimulus']['rate_hz']:g} Hz per stimulated neuron.\n")
    w("| condition | MN9 left (Hz) | MN9 right (Hz) | spikes / trial | active neurons / trial | film trial (seed) |\n|---|---|---|---|---|---|")
    for key, label in [("A_sugar", "A sugar"), ("B_bitter", "B bitter"), ("C_sugar_bitter", "C sugar + bitter"), ("D_baseline", "D baseline")]:
        cc = conds[key]
        m, sd = cc["mn9_rate_hz_mean"], cc["mn9_rate_hz_sd"]
        w(f"| {label} | {m[0]:.1f} ± {sd[0]:.1f} | {m[1]:.1f} ± {sd[1]:.1f} | {cc['total_spikes_mean']:,.0f} | "
          f"{cc['active_neurons_mean']:,.0f} | {cc['representative_seed']} |")
    w("")
    w("(mean ± s.d. over trials; MN9 sides from annotation v3.1.0.) **Representative trial**: for each condition the film "
      "shows the one trial whose MN9 rate (mean of the two MN9 neurons) is closest to the condition's mean; ties (all "
      "trials at 0 Hz in B and D) are broken by the total spike count closest to the mean, then the lowest seed. "
      "Chosen seeds: " + ", ".join(f"{k} → {conds[k]['representative_seed']}" for k in ("A_sugar", "B_bitter", "C_sugar_bitter", "D_baseline")) + ".\n")

    # spikes by colour class (non-stimulated neurons), from the spike files
    import numpy as np
    import pandas as pd

    nd = pd.read_parquet(ROOT / "data/processed/neurons.parquet")
    cls = nd.color_class.to_numpy()
    pos = {r: i for i, r in enumerate(nd.root_id)}
    stim_ix = [pos[r] for r in exp["stimulus"]["sugar_root_ids"] + exp["stimulus"]["bitter_root_ids"]]
    share = {}
    w("Spikes per trial of non-stimulated neurons by colour class (mean of 30 trials):\n")
    w("| condition | excitatory (amber) | inhibitory (cyan) | other (white) | inhibitory share |\n|---|---|---|---|---|")
    for key in ("A_sugar", "B_bitter", "C_sugar_bitter"):
        sp = np.load(ROOT / f"results/spikes/{key}.npz")
        nn = sp["neurons"][~np.isin(sp["neurons"], stim_ix)]
        cnt = pd.Series(cls[nn]).value_counts() / conds[key]["n_trials"]
        e_, i_, o_ = cnt.get("excitatory", 0.0), cnt.get("inhibitory", 0.0), cnt.get("other", 0.0)
        share[key] = (e_, i_, o_, i_ / max(e_ + i_ + o_, 1e-9))
        w(f"| {key} | {e_:,.0f} | {i_:,.0f} | {o_:,.0f} | {100 * share[key][3]:.1f} % |")
    a_, c_ = share["A_sugar"], share["C_sugar_bitter"]
    w(f"\nThe brief expected inhibitory (cyan) activity to visibly rise in experiment C. In the simulation it does not rise "
      f"in absolute terms: inhibitory spikes fall from {a_[1]:,.0f} to {c_[1]:,.0f} per trial, excitatory spikes fall more "
      f"({a_[0]:,.0f} → {c_[0]:,.0f}), so inhibition's share of the activity rises from {100 * a_[3]:.1f} % to "
      f"{100 * c_[3]:.1f} %. The film shows the spikes exactly as simulated and makes no on-screen claim about cyan "
      "activity rising.\n")
    w("### Validation (section 5 of the brief) — rendering is blocked unless all pass\n")
    t = val["tests"]
    w(f"Overall: **{'ALL PASSED' if val['all_passed'] else 'FAILED'}** (`results/validation.json`, {val['created_utc']}).\n")
    d1 = t["1_data_integrity"]
    w(f"1. **Data integrity** — {'pass' if d1['passed'] else 'FAIL'}. Checks:")
    for k, v in d1["checks"].items():
        w(f"   - {k}: {'yes' if v else 'NO'}")
    t2 = t["2_sugar_drives_mn9"]
    w(f"2. **Sugar drives MN9** — {'pass' if t2['passed'] else 'FAIL'}. MN9 at 150 Hz sugar input: "
      + ", ".join(f"{s} {fmt_mean_sd(x)} Hz" for s, x in t2["mn9_rate_hz"].items())
      + f". Criterion: {t2['criterion']}. flypoke reports {t2['flypoke_reported_hz']['right']:.1f} / "
        f"{t2['flypoke_reported_hz']['left']:.1f} Hz (right / left) at its own settings; this model at flypoke's settings "
        f"gives {t2['this_model_at_flypoke_settings_hz']['right']:.1f} / {t2['this_model_at_flypoke_settings_hz']['left']:.1f} Hz (see 6c).")
    t3 = t["3_bitter_does_not_drive_mn9"]
    w(f"3. **Bitter alone does not drive MN9** — {'pass' if t3['passed'] else 'FAIL'}: "
      + ", ".join(f"{s} {fmt_mean_sd(x)} Hz" for s, x in t3["mn9_rate_hz"].items()) + f" ({t3['criterion']}).")
    t4 = t["4_bitter_suppresses_sugar"]
    w(f"4. **Sugar + bitter < sugar** — {'pass' if t4['passed'] else 'FAIL'}: "
      + ", ".join(f"{s} {fmt_mean_sd(x)} Hz (−{t4['reduction_vs_sugar'][s] * 100:.0f} %)" for s, x in t4["mn9_rate_hz"].items())
      + f"; Welch t = {t4['welch_t_test_pair_mean']['t']:.1f}, p = {t4['welch_t_test_pair_mean']['p']:.1e}.")
    w(f"5. **Baseline silent** — {'pass' if t['5_baseline_silent']['passed'] else 'FAIL'}: 0 spikes in every one of the "
      f"{conds['D_baseline']['n_trials']} trials (the model has no spontaneous input).")
    t6 = t["6_determinism"]
    w(f"6. **Determinism** — {'pass' if t6['passed'] else 'FAIL'}: seed {t6['seed']} run twice gives identical spike "
      f"trains ({t6['spikes']:,} spikes); a different seed gives different trains.\n")

    cr = val["cross_checks"]
    w("### 6a. Against the authors' published outputs\n")
    w("The authors' repository contains the stored output of their own Brian2 runs (`results/example/`, snapshot 630, "
      "21 sugar GRNs, 30 trials). The same experiment re-run with this implementation (30 trials):\n")
    w("| input | neuron | this model (Hz) | authors' output (Hz) | difference / s.e. | Welch p |\n|---|---|---|---|---|---|")
    for rate in ("100Hz", "200Hz"):
        for rid, x in cr["a_published_outputs_630"][rate]["mn9"].items():
            w(f"| {rate} | MN9 {rid} | {fmt_mean_sd(x['ours'])} | {fmt_mean_sd(x['authors'])} | {x['diff_in_se']:+.2f} | {x['welch']['p']:.2f} |")
    for rate in ("100Hz", "200Hz"):
        s = cr["a_published_outputs_630"][rate]["spikes_per_trial"]
        w(f"\nSpikes per trial at {rate}: {s['ours']['mean']:,.0f} (this model) vs {s['authors']:,.0f} (authors).")
    w(f"\nResult: {'pass' if cr['a_published_outputs_630']['passed'] else 'FAIL'} ({cr['a_published_outputs_630']['criterion']}).\n")

    w("### 6b. Against the authors' Brian2 code\n")
    b2 = cr["b_brian2"]
    me = b2.get("micro_equivalence", {})
    fe = b2.get("fullnet_equivalence", {})
    w("The authors' `model.py` was run unmodified with Brian2 2.5.1 and NumPy 1.24 (their environment.yml versions) in a "
      "separate virtual environment.\n")
    if me:
        w(f"- **Step-level equivalence, small networks**: {me['description']}. Spike trains identical in all "
          f"{len(me['runs'])} runs; largest membrane-potential difference "
          f"{max(r['max_abs_dv_mV'] for r in me['runs']):.1e} mV (floating-point rounding).")
    if fe:
        w(f"- **Full network, identical input**: {fe['description']}. Spikes: {fe['spikes_ours']:,} (this model) and "
          f"{fe['spikes_brian2']:,} (Brian2), **{fe['common']:,} identical**, first difference: {fe['first_difference']}. "
          f"MN9 spikes {fe['mn9_ours']} vs {fe['mn9_brian2']}.")
    fn = b2.get("full_network_poisson")
    if fn:
        comp = fn["comparison_with_this_model"]
        w(f"- **Full network, Brian2's own Poisson input**: {fn['trials']} Brian2 trials vs {comp['left']['ours']['n']} trials of this "
          "model (paper sugar GRNs, 150 Hz):")
        for s in ("left", "right"):
            x = comp[s]
            w(f"  - MN9 {s}: Brian2 {fmt_mean_sd(x['brian2'])} Hz, this model {fmt_mean_sd(x['ours'])} Hz, difference "
              f"{x['diff_in_se']:+.2f} s.e. (Welch p = {x['welch']['p']:.3f})")
        sp = comp["spikes_per_trial"]
        w(f"  - spikes per trial: Brian2 {sp['brian2']['mean']:,.0f}, this model {sp['ours']['mean']:,.0f}")
        an = fn.get("all_neurons")
        if an:
            gr = an["grn_rate_hz"]
            w(f"  - **every neuron** (the criterion): of the {an['active_neurons']} neurons active in either implementation, "
              f"{an['significant_after_bonferroni']} differ after Bonferroni correction (threshold p < {an['bonferroni_threshold']:.1e}); "
              f"{an['p_below_0_001']} have p < 0.001 ({an['expected_by_chance_at_0_001']:.2f} expected by chance). The smallest "
              "p-values: " + "; ".join(f"{x['cell_type']} ({x['side']}) {x['brian2_hz']:.1f} vs {x['ours_hz']:.1f} Hz, p = {x['p']:.4f}"
                                       for x in an["smallest_p"][:3])
              + f". Stimulated GRNs fire at {gr['brian2']:.2f} Hz (Brian2) and {gr['ours']:.2f} Hz (this model). The right-MN9 "
              "difference is therefore what 455 comparisons produce by chance; with identical input the two implementations "
              "produce identical spikes (above).")
    w(f"\nResult: {'pass' if b2['passed'] else 'FAIL'}.\n")

    w("### 6c. Against flypoke\n")
    fp = cr["c_flypoke"]
    w("flypoke (github.com/vshapenko/flypoke, commit 24814fe) uses the annotation classes (129 sugar/water, 65 bitter GRNs), "
      "connections ≥ 5 synapses, annotation `top_nt` signs, exponential-Euler integration and direct Poisson spikes; it "
      "does not discard input to refractory neurons. Settings matched to flypoke's `feeding` command (150 Hz, 5 trials, "
      "seeds 0–4):\n")
    w("| condition | flypoke README | flypoke code on this connectome | this model, flypoke's network | this model, authors' network |\n|---|---|---|---|---|")
    for k in ("sugar", "bitter", "sugar + bitter"):
        a, b_, cc, dd = fp["flypoke_readme_table"][k], fp["flypoke_code_on_this_connectome"][k], fp["this_model_flypoke_settings"][k], fp["this_model_authors_network_annotation_classes"][k]
        fmt = lambda x: f"MN9 R {x['mn9_right']:.1f} / L {x['mn9_left']:.1f} Hz, ingestion MNs {x['ingestion_mean']:.1f} Hz, {x['active']:,} active"
        w(f"| {k} | {fmt(a)} | {fmt(b_)} | {fmt(cc)} | {fmt(dd)} |")
    w("")
    w(f"flypoke's table reproduced exactly: **{fp['flypoke_readme_reproduced_exactly']}**. At flypoke's settings this model "
      f"gives the same qualitative result with MN9 {fp['ratio_mn9_right']:.2f}× flypoke's rate; the difference comes from "
      "the Brian2 semantics above (flypoke keeps input that arrives during refractoriness and integrates with exponential "
      "Euler). The same semantics explain why strongly driven pathways recruit more neurons in flypoke (e.g. bitter: "
      f"{fp['flypoke_code_on_this_connectome']['bitter']['active']} active neurons in flypoke vs "
      f"{fp['this_model_flypoke_settings']['bitter']['active']} here, on the identical network and stimulus): input kept "
      "through the refractory period lets a strongly driven neuron fire again immediately. \"Active\" uses flypoke's "
      "definition (mean rate over the trials > 1 Hz, minus the stimulated neurons). "
      "The last column shows the whole annotation classes in the exact model: MN9 behaves as expected, but "
      "thousands of neurons become active (see section 6, stimulus identification). "
      f"Result: {'pass' if fp['passed'] else 'FAIL'} ({fp['criterion']}).\n")

    # ------------------------------------------------------------------ film
    w("## 7. The film: what is data and what is a visual aid\n")
    w("**Data (from the simulation or the connectome):**\n")
    w("- Every neuron is one point at its true position (section 3). Resting neurons are dim grey-blue points of constant "
      "apparent size.")
    w("- Every flash is a spike of the representative trial of the condition shown. The glow of neuron i at brain time t "
      "is Σ exp(−(t − s)/8 ms) over its spikes s ≤ t (≈ 95 % decayed after 25 ms of brain time), evaluated at every "
      "sub-frame from the stored spike times. No spike is added, removed or moved.")
    w("- Spike colour: amber = excitatory, cyan = inhibitory in the model (authors' sign), soft white = neurons predicted "
      "to use dopamine, serotonin or octopamine (excitatory in the model), green = stimulated sugar GRNs, violet = "
      "stimulated bitter GRNs, white with a ring marker = MN9.")
    w("- Brain clock: brain time of the trial in ms; slow-motion factor shown on screen (25× in the master, 10× in the "
      "vertical cut); film time = brain time × factor.")
    w("- MN9 readout: spikes of each MN9 neuron in the last 100 ms of brain time × 10 (Hz); after the trial the total "
      "spike count of the trial. The end-of-C comparison shows the MN9 spike counts of the two representative trials.")
    w("- Long exposure: every neuron that spiked in trial A, B or C is drawn in that trial's colour with brightness "
      "∝ √(its spike count), accumulating in brain-time order (the three 1 s trials replayed together over 10 s of film). "
      "During it the resting neurons fade to 12 % so that the points of light are the spikes; the glass shell keeps the "
      "brain's outline.\n")
    w("**Visual aids (not part of the model):**\n")
    w(f"- **Pathway highlight.** {len(pw['neurons'])} neurons chosen from the representative sugar trial: MN9 (2), the "
      f"{pw['rule']['K1']} neurons with the largest (spikes × excitatory synapses onto MN9), the {pw['rule']['K2']} with the "
      f"largest (spikes × synapses onto those), and the {pw['rule']['K0']} stimulated sugar GRNs with the largest input to "
      "them. Their skeletons are drawn as thin lines, dim when silent and lit with the same spike glow as their points "
      "when they fire. Arcs are drawn for every excitatory connection of ≥ 5 synapses from one level to the next "
      f"({len(pw['arcs'])} arcs). **When a pathway neuron spikes, a small pulse travels along each of its arcs in 30 ms of "
      "film time. This travel is a visual aid: the model has no propagation along wires, only a fixed 1.8 ms "
      "synaptic delay.**")
    w("- **Sugar glow before experiment A.** While the camera glides to the taste region, the 20 sugar GRNs are marked by "
      "a steady soft green glow (a label, not activity); it fades before the trial starts.")
    w("- **Fly inset.** A line drawing labelled \"illustration\". Its proboscis extension follows the simulated MN9 rate "
      "(mean of both MN9, last 50 ms of brain time; 60 Hz = fully extended). The model has no muscles or behaviour; MN9 "
      "is the motor neuron that extends the proboscis in real flies.")
    w("- Brain shell (Fresnel rim), bloom, ACES tone mapping, grain, camera motion and 4-sub-frame motion blur are "
      "presentation only.\n")
    w("Pathway neurons:\n")
    lvl = {0: "input (sugar GRN)", 1: "2 steps from MN9", 2: "1 step from MN9", 3: "MN9"}
    w("| level | root id | cell type | side | spikes in trial |\n|---|---|---|---|---|")
    for r in pw["neurons"]:
        w(f"| {lvl[r['level']]} | {r['root_id']} | {r['cell_type'] or ''} | {r['side']} | {r['spikes']} |")
    w("")
    w("### Timeline\n")
    from render.film import FORMATS, FilmData, Timeline

    fd = FilmData()
    for fmt_name in ("master", "vertical"):
        tl = Timeline(FORMATS[fmt_name], fd)
        f = FORMATS[fmt_name]
        mmss = lambda t: f"{int(t // 60)}:{t % 60:05.2f}"
        w(f"**{fmt_name}** ({f.size[0]}×{f.size[1]}, {f.fps} fps, {f.subframes} sub-frames, slow motion {f.slow:.0f}×, "
          f"duration {mmss(tl.duration)}):\n")
        w("| film time | what |\n|---|---|")
        w(f"| {mmss(tl.darkness[0])}–{mmss(tl.darkness[1])} | darkness |")
        w(f"| {mmss(tl.reveal[0])}–{mmss(tl.reveal[1])} | neurons fade in region by region (central brain, optic lobes, sensory), camera orbits |")
        w(f"| {mmss(tl.glide[0])}–{mmss(tl.glide[1])} | camera glides to the subesophageal zone; sugar GRNs marked green |")
        for seg in tl.segments:
            w(f"| {mmss(seg.start)}–{mmss(seg.end)} | experiment {seg.key}: brain clock 0 → 1000 ms from {mmss(seg.t0)} to {mmss(seg.t1)} |")
        w(f"| {mmss(tl.long[0])}–{mmss(tl.long[1])} | pull back; long exposure accumulates from {mmss(tl.accum[0])} to {mmss(tl.accum[1])} |")
        w(f"| {mmss(tl.credits[0])}–{mmss(tl.credits[1])} | credits; final line |\n")
        w("| caption | on screen |\n|---|---|")
        for a, b, text in tl.captions:
            w(f"| {text.format(**fd.numbers).replace(chr(10), ' ')} | {mmss(a)}–{mmss(b)} |")
        w("")
    w("Deviation from the brief's timing: with the same 25× slow motion for all three experiments (1 s of brain time = "
      "25 s of film, inside the requested 25–35 s), experiments B and C need 28 s each instead of 25 s, so the master runs "
      "2:36 instead of ~2:30. The vertical cut uses 10× slow motion so the same beats fit ~60 s.\n")
    w("### Captions and on-screen numbers\n")
    w(f"- \"{nums['neurons']:,} neurons. {nums['connections']:,} connections.\" — `results/prepare_log.json` "
      "(neurons simulated; connections in the authors' v783 table).")
    w(f"- Stimulus lines — `results/experiments.json` ({nums['sugar_n']} sugar GRNs, {nums['bitter_n']} bitter GRNs, "
      f"{nums['rate_hz']:g} Hz).")
    for key in ("A_sugar", "B_bitter", "C_sugar_bitter"):
        x = nums[key]
        w(f"- {key}: film trial seed {x['representative_seed']}, MN9 spikes in the trial {x['mn9_spikes_trial']} "
          f"(left, right), {x['spikes_trial']:,} spikes, {x['active_neurons_trial']} active neurons.")
    w("- Caption wording differs from the brief in two places to stay accurate: \"One neuron type, MN9, decides: eat.\" "
      "(there are two MN9 neurons, one per side) and \"Bitter. The decision neurons stay silent.\" (plural).\n")

    w("## 8. Rendering\n")
    w("moderngl (OpenGL 3.3 core) through a headless EGL context. This build machine has no GPU, so Mesa's llvmpipe "
      "rasterised on the CPU. Points and lines are drawn additively into a float32 HDR buffer; 4 sub-frames per output "
      "frame (180° shutter) are accumulated for motion blur; the brain shell once per frame. Post: 6-level bloom "
      "(13-tap downsample, tent upsample), ACES filmic tone curve (Narkowicz fit), gamma, background #030407, fine grain. "
      "Overlays (Inter) are composited in sRGB. Encoding: ffmpeg libx264, yuv420p, BT.709; the 1080p version is a "
      "Lanczos downscale of the master. `render/cpu.py` is a slow NumPy splatting fallback for previews without GL.\n")
    w("QA: one defect appeared during development — a single non-finite pixel from the shell shader (`pow` of a "
      "slightly negative base when |n·v| rounds above 1) that the bloom chain spread into a dark block. The shader now "
      "clamps its input and the bloom and final passes discard non-finite values; `tests/qa_video.py --nan master 40` "
      "re-renders 40 random frames at full resolution and confirms the HDR buffer is finite in every one.\n")

    w("## 9. Reproduce\n")
    w("```\npip install -r requirements.txt   # plus ffmpeg, Mesa EGL, fonts-inter\npython fetch.py\npython prepare.py\n"
      "python -m sim.run\npython -m render.pathway\npython -m sim.validate          # Brian2 checks: see sim/brian2_reference.py, tests/\n"
      "python -m render.film master && python -m render.film 1080p\npython -m render.film vertical && python -m render.film poster\n"
      "python notes.py\npython -m pytest tests/\n```\n")

    w("## 10. Credits\n")
    w("- FlyWire Consortium; Dorkenwald et al. 2024, *Nature* 634:124–138, \"Neuronal wiring diagram of an adult brain\".")
    w("- Schlegel et al. 2024, *Nature* 634:139–152, \"Whole-brain annotation and multi-connectome cell typing of Drosophila\".")
    w("- Eckstein et al. 2024, *Cell* 187:2574–2594 (neurotransmitter predictions).")
    w("- Berg et al. 2025 (bioRxiv 10.1101/2025.10.09.680999) and Matsliah et al. 2024 (*Nature*): annotation updates in "
      "flywire_annotations v3.1.0 (requested citation for versions ≥ 3.0.0).")
    w("- Shiu et al. 2024, *Nature* 634:210–219, \"A Drosophila computational brain model reveals sensorimotor processing\"; "
      "code and v783 files: github.com/philshiu/Drosophila_brain_model (MIT).")
    w("- flypoke (github.com/vshapenko/flypoke, MIT) — cross-checks; navis-flybrains (GPL v3) — FlyWire brain mesh; "
      "FlyWire release-783 skeletons (gs://flywire_v141_m783); Brian2; Inter typeface.\n")
    w("The on-screen credits carry the same list (condensed in the vertical cut). The data licence wording could not be "
      "confirmed against the primary FlyWire / Zenodo pages from this environment (section 2); the credits follow the "
      "citation requirements stated in the flywire_annotations README.\n")
    w("## 11. Limitations\n")
    w("- The model is a point-neuron LIF model without plasticity, neuromodulation, gap junctions or behaviour; it shows "
      "what the wiring alone does under these assumptions, as in Shiu et al.")
    w("- The official Zenodo connection table and skeleton archive were unreachable from the build environment; see "
      "section 2 for the substitutes and the evidence that they match.")
    w("- The FlyWire data licence wording could not be checked against the primary source from this environment.")
    w("- 1 of the paper's 21 sugar GRNs and 1 of its 21 bitter GRNs no longer exist under the same root id in release 783 "
      "and are not stimulated.")
    (ROOT / "NOTES.md").write_text("\n".join(L) + "\n")
    print(f"wrote {ROOT / 'NOTES.md'} ({len(L)} lines)")


if __name__ == "__main__":
    main()
